Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
