name: JRuby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 'jruby' ]
    name: Test Ruby ${{ matrix.ruby }}
    steps:
    - name: Install libraries
      run: sudo apt install haveged
    - uses: actions/checkout@v2
    - name: Set up RVM Package
      run: |
        curl -sSL https://get.rvm.io | bash
    - name: Set up Ruby
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install ${{ matrix.ruby }}
        rvm --default use ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        source $HOME/.rvm/scripts/rvm
        gem install bundler --no-document
        bundle install
    - name: Run test
      run: |
        source $HOME/.rvm/scripts/rvm
        rake test
