name: Dependency Review

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependency-review:
    uses: chargehound/security-workflows-public/.github/workflows/dependency-review.yml@main
    secrets:
      DATADOG_API_KEY: ${{ secrets.DATADOG_PAYPAL_QA_TOKEN }}      